### ISSUE TITLE
Document JackadocsMain etc.

### ISSUE THREAD

**Issue by Madoc** [jackadull/jackadocs#13]
Jackadocs version 0.3.0 introduced `JackadocsMain` and a new handling of project meta information.
Add documentation for this to the readme.

- [ ] `JackadocsMain`
- [ ] Info type and `JackadocsProjectInfo`
- [ ] `RootChapter`
- [ ] No more manual chapter ID
- [ ] Implicit conversion from `String` to `NodeSeq` in the scope of `Chapter`
- [ ] TOC support (see #6)
- [ ] `ChapterNumbering` nesting (see #8)
- [ ] Automated docs re-generation (see #10)
